spring:
  application:
    name: inolog
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    # NON_KEYWORDS=USER > user 테이블 사용을 위해 추가
    url: jdbc:h2:mem:inolog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  # 서버 구동 시 data.sql 읽음
  sql:
    init:
      mode: always

  # oauth2 설정
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li38kZEoCpkkwCqQ
            client-secret: 681f65bfd36601b8f77a886cb2bd679044dbe745
            redirect-uri: http://localhost:5173/api/login/oauth2/code/github

inolog:
  jwt-key: 3l3Cw10+O7gzomDsD4c7F1D7v3r3LBJ8MvMx8DJnQKE=

