spring:
  application:
    name: inolog
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:inolog
    username: sa
    password:
    driver-class-name: org.h2.Driver